#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PYTHON="$ROOT_DIR/.venv-pathagon-gnn/bin/python"
WORKSPACE="$ROOT_DIR/research/20260901-jepa-afterstate/workspace"
mkdir -p "$WORKSPACE"

if [[ ! -x "$PYTHON" ]]; then
  echo "missing learner environment: $PYTHON" >&2
  exit 2
fi

# The game archive is generated by the exact Rust search engine so the replay
# fine-tune and the JEPA transition corpus share the same rules authority.
cargo run --manifest-path "$ROOT_DIR/pathagon/engine-rs/Cargo.toml" \
  --release --bin pathagon-selfplay -- \
  --games "${REPLAY_GAMES:-4}" \
  --max-plies "${REPLAY_MAX_PLIES:-20}" \
  --opening-random-plies 4 \
  --opponent deep-search \
  --depth 2 --beam 64 --nodes 12000 \
  --jsonl --seed "${REPLAY_SEED:-2026090104}" \
  > "$WORKSPACE/rust-replay.jsonl"

GAMES="${TRANSITION_GAMES:-8}" \
MAX_PLIES="${TRANSITION_MAX_PLIES:-12}" \
ACTIONS_PER_STATE="${ACTIONS_PER_STATE:-16}" \
SEED="${TRANSITION_SEED:-2026090101}" \
bash "$ROOT_DIR/research/20260901-jepa-afterstate/scripts/generate_smoke.sh" \
  > "$WORKSPACE/transition-export.log"

INIT_CHECKPOINT="${INIT_CHECKPOINT:-$ROOT_DIR/research/20260901-strong-teacher-10k-games/workspace/retraining-mixed-final/gnn-policy-value.pt}"
"$PYTHON" "$ROOT_DIR/research/20260901-jepa-afterstate/scripts/train_afterstate.py" \
  --input "$WORKSPACE/rust-transitions.jsonl" \
  --output "$WORKSPACE/jepa-smoke.pt" \
  --init-checkpoint "$INIT_CHECKPOINT" \
  --replay-input "$WORKSPACE/rust-replay.jsonl" \
  --steps "${JEPA_STEPS:-2}" \
  --batch-size "${JEPA_BATCH_SIZE:-2}" \
  --replay-steps "${REPLAY_STEPS:-2}" \
  --device cpu \
  > "$WORKSPACE/training-report.json"

(
  cd "$ROOT_DIR/research/20260824-gnn-cnn-lab"
  PYTHONPATH="$ROOT_DIR/research/20260824-gnn-cnn-lab" "$PYTHON" -m python.export_gnn \
    --checkpoint "$WORKSPACE/jepa-smoke-policy-value.pt" \
    --output "$WORKSPACE/jepa-smoke.onnx" \
    --device cpu
) > "$WORKSPACE/export-onnx-report.json"

cargo run --manifest-path "$ROOT_DIR/pathagon/engine-rs/Cargo.toml" \
  --release --features inference --bin pathagon-selfplay -- \
  --games "${ARENA_GAMES:-2}" \
  --max-plies "${ARENA_MAX_PLIES:-12}" \
  --opening-random-plies 2 \
  --onnx "$WORKSPACE/jepa-smoke.onnx" \
  --opponent filter-search \
  --depth 2 --beam 64 --nodes 12000 \
  --jsonl --seed "${ARENA_SEED:-2026090105}" \
  > "$WORKSPACE/search-arena.jsonl"

echo "end-to-end JEPA/search smoke complete: $WORKSPACE"
